[2024-02-09T19:01:01.888+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
