[2024-01-31T19:30:23.104+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:30:21.731230+00:00 [queued]>
[2024-01-31T19:30:23.108+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:30:21.731230+00:00 [queued]>
[2024-01-31T19:30:23.108+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-31T19:30:23.114+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-01-31 19:30:21.731230+00:00
[2024-01-31T19:30:23.117+0000] {standard_task_runner.py:60} INFO - Started process 65 to run task
[2024-01-31T19:30:23.121+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-01-31T19:30:21.731230+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp1s4tmmhw']
[2024-01-31T19:30:23.123+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask yellow_cabs_upload
[2024-01-31T19:30:23.153+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:30:21.731230+00:00 [running]> on host 8ff05e883b9e
[2024-01-31T19:30:23.365+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T19:30:21.731230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T19:30:21.731230+00:00'
[2024-01-31T19:30:28.561+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 29, in yellow_cabs_upload
    df = pd.to_csv(table)
AttributeError: module 'pandas' has no attribute 'to_csv'
[2024-01-31T19:30:28.567+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240131T193021, start_date=20240131T193023, end_date=20240131T193028
[2024-01-31T19:30:28.609+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task yellow_cabs_upload (module 'pandas' has no attribute 'to_csv'; 65)
[2024-01-31T19:30:28.634+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T19:30:28.719+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
